name: Site name
description: Site description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://robinparisi.github.io" # the base hostname & protocol for your site
markdown: redcarpet
source: ./src
destination: ./dist
keep_files: [assets]
markdown: kramdown
